[application]
asset_dir = "assets"
default_platform = "web"
name = "nemesisx00-github-io"
out_dir = ""

[bundle]
copyright = "Copyright 2023 Peter Lunneberg"
identifier = "io.github.nemesisx00"
publisher = "Peter Lunneberg"

[web.app]
title = "Peter Lunneberg - Software Developer"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "assets"]

[web.resource]

[web.resource.dev]

[web.wasm_opt]
level = "z"
